***EXPERIMENT 2:*** Numerical Python ***NUMPY***


In [11]:
import numpy as np

In [46]:
x = np.random.random ((5,5))

print("Array X:\n", x)

Array X:
 [[0.74944939 0.69720597 0.358831   0.92584958 0.90293109]
 [0.31711053 0.45983175 0.40430587 0.6400442  0.2127875 ]
 [0.09283036 0.59579767 0.06726429 0.75741911 0.44665079]
 [0.48164289 0.44103233 0.34456082 0.79647972 0.10315822]
 [0.89970166 0.02752572 0.39304409 0.6073242  0.15116189]]


In [48]:
mean = x.mean()
z = (x - mean) / x.std()

print("Normalized Array x:\n", z)

Normalized Array x:
 [[ 1.0151823   0.82196487 -0.42948354  1.66758204  1.58282013]
 [-0.58378283 -0.05594165 -0.26129897  0.61055735 -0.96961187]
 [-1.4132622   0.44691568 -1.50781593  1.04465756 -0.10469019]
 [ 0.02472481 -0.12546955 -0.48226047  1.18911961 -1.37506556]
 [ 1.57087638 -1.65478536 -0.3029496   0.48954547 -1.19752847]]
